### ISSUE TITLE
JOSS review: Functionality for predicting densities

### ISSUE THREAD

**Issue by salbalkus** [nppackages/lpcde#9]
Raising as part of JOSS review openjournals/joss-reviews#7241

During my review, I tested the package's functionality on a few different simulated conditional densities (gamma/beta, etc.) with different estimator hyperparameter settings. All outputs appeared reasonable -- great job implementing a relatively complex statistical procedure in R. However, I do have one somewhat major criticism regarding the functionality of the software: **it is relatively difficult to obtain conditional density predictions for each unit of a given dataset.**

To elaborate, based on the code examples, it seems as though the API is oriented towards visualization of an entire conditional density for a fixed $x$ value. For instance, consider the following simulation setup:

```
library("lpcde")
set.seed(42)
n=100
x_data = matrix(rbeta(n, 2, 4))
y_data = matrix(rgamma(n, 10, 1/x_data))
```

It is very easy to fit the model across a small grid of $y$ values with just two lines of code:

```
y_grid = seq(from=1, to=5, length.out=10)
model1 = lpcde::lpcde(x_data=x_data, y_data=y_data, y_grid=y_grid, x= 0.5, bw = 0.5)
```

The grid-based approach is nice for visualization if estimating the entire density curve is the end goal. However, many practical applications necessitate estimating conditional density values for each unit of a dataset to perform some downstream analysis. For example, many counterfactual mean estimators for a continuous treatment in causal inference require first estimating the conditional density of the treatment given covariates for each unit, and then reweighting an outcome based on the conditional density (for example, [Diaz and van der Laan (2012)](https://pubmed.ncbi.nlm.nih.gov/21977966/), [Haneuse and Rotnizky (2013)](https://pubmed.ncbi.nlm.nih.gov/23913589/) or even something like [Schindl, Shen, and Kennedy (2024)](https://arxiv.org/abs/2409.11967)). 

Based on the API, one would think this could be accomplished by replacing `y_grid` with `y_data` and `x` with `x_data`. However, doing so runs into multiple issues. First, `x` does not seem to be able to take in a vector input -- I get this result:

```
> model1 = lpcde::lpcde(x_data=x_data, y_data=y_data, y_grid=y_grid, x=matrix(c(0.3, 0.6), ncol = 2), bw = 0.5)
> Error in s_mat %*% e_vec : non-conformable arguments
In addition: Warning messages:
1: In sweep(x_data, 2, x) :
  STATS is longer than the extent of 'dim(x)[MARGIN]'
2: In sweep(x_sorted, 2, x) :
  STATS is longer than the extent of 'dim(x)[MARGIN]'
```

Maybe I am providing the input incorrectly, but either way, it is not obvious how to compute estimates for multiple `x` values. Second, consider the following line, which takes about 30 seconds to run on my machine:

```
model1 = lpcde::lpcde(x_data=x_data, y_data=y_data, y_grid=y_data, x= 0.5, bw = 0.5)
```

It yields the exact same predictions as the following, which runs in under 2 seconds:

```
preds = vector(length = 100)
for(i in 1:100){
model2 = lpcde::lpcde(x_data=x_data, y_data=y_data, y_grid=y_data[i], x=0.5, bw = 0.5)
preds[i] = model2$Estimate[3] # or extract whatever statistics you like...
}
```

which leads me to believe something redundant is going on under the hood that I don't quite understand. Third, there seems to be no way to, after the model is fit, apply it to obtain estimates on a new set of data. In any case, I would recommend implementing something like a `predict` method to perform inference on an arbitrary dataset, in order to separate these two uses cases and allow obtaining estimates on a new set of data.

**Comment by rajitachandak** [comment]
We would like to address this comment in three separate points:

 (a) The difference in run time identified for two methods of implementing lpcde is due to the fact that the original implementation for lpcde also computes the full covariance matrix, which when given many grid points, can be quite slow to compute (of order n^3). To allow more flexibility (as in your example, where the covariance estimate is not needed), we have added a new optional input cov_flag to the lpcde function which can take on three different values:
        (1) "full": this is the original implementation, the function will compute the entire covariance matrix (and therefore allow confidence interval and band construction),
        (2) "diag": this will only compute the diagonal entries of the covariance matrix (i.e. the standard errors, only pointwise confidence intervals can be computed), and
        (3) "off": no entries of the covariance matrix are estimated.

  (b) For estimating the density over different conditioning values (x), a for loop will need to be used outside of calling the lpcde function. This is to ensure the inference capabilities (i.e. confidence intervals and uniform confidence bands) of the function can still be used, if desired. We have added a note regarding this in the description of the lpcde function.

  (c) It turns out our implementation lpcde already works for prediction on a new dataset directly. Below is a simple illustration of how this can be coded up:

Suppose we choose different data to "train" our estimator and to "test" it on an unseen dataset. In this case, a common method is to randomly subset the data into training and testing.
We start with the same simulation setup as in your example:
```
     library("lpcde")
      set.seed(32)
      n=1000
      x_data = matrix(rbeta(n, 2, 4))
      y_data = matrix(rgamma(n, 10, 1/x_data))
```
Now, we want to split the data. This can be done with the following three lines of code:

```
      #use 95% of dataset as training set and 5% as test set
      sample = sample(c(TRUE, FALSE), nrow(y_data), replace=TRUE, prob=c(0.95,0.05))
      y_train  = y_data[sample, ]
      x_train = x_data[sample, ]
      y_test   = y_data[!sample, ]
```
Now we simply input the y_test as the grid of evaluation points to lpcde:
```
   prediction_model = lpcde::lpcde(x_data=x_train, y_data=y_train, y_grid=y_test, x=0.5, bw=0.5, cov_flag="off")
```
If we wanted to extract only the point estimates of this model (as is usually the output of the predict function), we could run

``` 
coef(prediction_model)
```

Additionally, we note that the predict function only works effectively when there is a closed-form solution for evaluating the function at new data points. Since our estimator is nonparametric (of the local smoothing variety), it will require to construct a new estimate for each new evalulation point of interest (e.g., the bandwidth needs to be re-estimated, and the local data contributes differently as determined by the equivalent kernel). If the objective is to simply extract the point estimates, we recommend in the documentation that the coef method can be used to extract only the estimates from the lpcde object.

**Comment by salbalkus** [comment]
This is fantastic. Thank you for clearing up this issue; the example you provided is perfect for helping users understand how to get predictions, and the `cov_flag` parameter is a great solution to allow users to easily compute predictions quickly. Very clear explanation!
